name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint and fmt check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Validate Taskfile
        run: task validate

      - name: Linting and fmt check
        run: task lint

  build:
    name: CI on Go
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Validate Taskfile
        run: task validate

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}

      - name: Start dependencies
        run: task deps-start

      - name: Running CI
        run: |
          task ci

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.txt

      - name: e2e
        run: |
          go build -o service ./service/
          nohup ./service/service &
          go run client/main.go
        working-directory: ./examples
        env:
          OTEL_EXPORTER_OTLP_INSECURE: true

      - name: Stop dependencies
        run: task deps-stop
