name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint and fmt check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: |
            go.sum
            vendor/modules.txt

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6.1
          args: --build-tags=integration -v
        env:
          GOFLAGS: -mod=vendor

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: |
            go.sum
            vendor/modules.txt

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Validate Taskfile
        run: task validate

      - name: Start dependencies
        run: task deps-start
        env:
          COMPOSE_PROJECT_NAME: patron-integration-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Running CI
        run: |
          task ci

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.txt

      - name: Stop dependencies
        run: task deps-stop
        if: always()
        env:
          COMPOSE_PROJECT_NAME: patron-integration-${{ github.run_id }}-${{ github.run_attempt }}

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: |
            go.sum
            vendor/modules.txt

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Validate Taskfile
        run: task validate

      - name: Start dependencies
        run: task deps-start
        env:
          COMPOSE_PROJECT_NAME: patron-e2e-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Run e2e tests
        run: |
          go build -o service ./service/
          nohup ./service/service &
          go run client/main.go
        working-directory: ./examples
        env:
          OTEL_EXPORTER_OTLP_INSECURE: true

      - name: Stop dependencies
        run: task deps-stop
        if: always()
        env:
          COMPOSE_PROJECT_NAME: patron-e2e-${{ github.run_id }}-${{ github.run_attempt }}
